"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$sudo\
$cmd_duration\
$time\
$status\
$shell\
$character"""
add_newline = false

[character]
success_symbol = "[λ](bold green)"

[line_break]
disabled = true

[cmd_duration]
show_milliseconds = true
min_time = 1

[git_branch]
truncation_length = 16

[time]
disabled = false

[python]
symbol = " "
